version: '3.3'
services:
  app:
    build: ./
    restart: always
    ports:
      - "9000:80"
    environment:
      - F5_USERNAME=admin
      - F5_PASSWORD=1qaz@WSX3edc\$RFV
      - F5_ROOT=172.16.66.153
      - DB_USERNAME=root
      - DB_PWD=p785084298
      - DB_HOST=172.16.66.97
